up

diff --git a/.bin/pr-checks b/.bin/pr-checks
--- a/.bin/pr-checks
+++ b/.bin/pr-checks
@@ -13,11 +13,12 @@ message () {
 STATUS=0
 
 message "Installing dependencies with yarn..."
-yarn install --frozen-lockfile 2>&1 || STATUS=$?
-if [ $STATUS -eq 1 ]; then
-   echo "yarn install failed"
-   exit 1
-fi
+RUN yarn install --frozen-lockfile
+#yarn install --frozen-lockfile 2>&1 || STATUS=$?
+#if [ $STATUS -eq 1 ]; then
+#   echo "yarn install failed"
+#   exit 1
+#fi
 
 # production build - needed for some of the subsequent checks, like storybook
 message "Running production build..."
