up

diff --git a/.bin/pr-checks b/.bin/pr-checks
--- a/.bin/pr-checks
+++ b/.bin/pr-checks
@@ -13,15 +13,15 @@ message () {
 STATUS=0
 
 message "Installing dependencies with yarn..."
-yarn install --frozen-lockfile 2>&1 || STATUS=$?
-if [ $STATUS -eq 1 ]; then
-   echo "yarn build failed"
-   exit 1
-fi
+yarn install --frozen-lockfile 2>&1 || exit 1
+#if [ $STATUS -eq 1 ]; then
+#   echo "yarn build failed"
+#   exit 1
+#fi
 
 # production build - needed for some of the subsequent checks, like storybook
 message "Running production build..."
-#cp ./docker/.env.docker.prod ./packages/venia-concept/.env
+cp ./docker/.env.docker.prod ./packages/venia-concept/.env
 yarn run build 2>&1 || STATUS=$?
 if [ $STATUS -eq 1 ]; then
    echo "yarn build failed"
